---
version: 5.7
package_suffix: 57

root_password: '+eswuw9uthUteFreyAqu'

global_config: {}
default_config:
  mysqldump:
    quick:
    quote-names:
    max_allowed_packet: 100M
  client:
    port: 3306
    socket: /var/run/mysqld/mysqld.sock
  mysqld_safe:
    pid-file: /var/run/mysqld/mysqld.pid
    socket: /var/run/mysqld/mysqld.sock
    nice: 0
  mysqld:
    server-id: "{{ server_index }}"
    datadir: /var/lib/mysql
    socket: /var/run/mysqld/mysqld.sock
    log-error: /var/log/mysqld.log
    pid-file: /var/run/mysqld/mysqld.pid
    log-bin:
    log_slave_updates:
    expire_logs_days: 7
    symbolic-links: 0
    wsrep_provider: /usr/lib/galera3/libgalera_smm.so
    wsrep_cluster_address: gcomm://
    binlog_format: ROW
    default_storage_engine: InnoDB
    wsrep_slave_threads: 8
    wsrep_log_conflicts:
    innodb_autoinc_lock_mode: 2
    wsrep_node_address: "{{ ansible_host }}"
    wsrep_cluster_name: percona-cluster
    wsrep_node_name: "percona-{{ server_index }}"
    pxc_strict_mode: ENFORCING
    wsrep_sst_method: xtrabackup-v2
    wsrep_sst_auth: replicator:replicator

root_user_config:
  client:
    host: localhost
    user: root
    password: "{{ root_password }}"
