---
# file: roles/haproxy/tasks/config.yml
- name: Configuring HAproxy
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: "{{ haproxy_config }}"
    validate: "{{ haproxy_bin }} -f %s -c"
  notify: reload haproxy
