_ansible: &ansible
    provider: ansible
    roles: percona-admin
    directory: ansible
    servers:
        - name.startswith=percona-db

percona:
    <<: *ansible
    playbooks: percona.yml

database:
    <<: *ansible
    playbooks: percona-db.yml

user:
    <<: *ansible
    playbooks: percona-user.yml
