
_ansible: &ansible
  provider: ansible
  roles: percona-admin
  config: ansible.cfg
  group_vars: variables


percona:
  <<: *ansible
  playbooks: percona.yml

database:
  <<: *ansible
  playbooks: percona-db.yml

user:
  <<: *ansible
  playbooks: percona-user.yml
