
_ansible: &ansible
  provider: ansible
  roles: percona-admin
  directory: ansible


percona:
  <<: *ansible
  playbooks: percona.yml

database:
  <<: *ansible
  playbooks: percona-db.yml

user:
  <<: *ansible
  playbooks: percona-user.yml
