replicator_password: "+eswuw9uthUteFreyAqu"
mysqlchk_password: "7t5sPjx98AmxJuzp00A34"

users_present: {}
default_users_present:
    replicator:
        password: "{{ replicator_password }}"
        privileges:
            - "*.*:RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT"
        host: "%"
    clustercheck:
        password: "{{ mysqlchk_password }}"
        privileges:
            - "*.*:PROCESS"
        host: "localhost"

users_absent: {}
default_users_absent:
    "":
