- block:
      - name: configure | stop service
        service:
            name: mysql
            state: stopped

      - name: configure | remove unused configurations
        file:
            path: "{{ item }}"
            state: absent
        with_items:
            - /etc/mysql/my.cnf.fallback
            - /etc/mysql/my.cnf.old
            - /etc/mysql/conf.d
            - /etc/mysql/percona-xtradb-cluster.cnf
            - /etc/mysql/percona-xtradb-cluster.conf.d

  when: _mysqld_installed.rc != 0

- name: configure | update configuration file
  template:
      src: my.cnf.j2
      dest: /etc/mysql/my.cnf
      owner: root
      group: root
      mode: 0644
  notify: restart percona-cluster

- block:
      - name: configure | bootstrap cluster
        command: /etc/init.d/mysql bootstrap-pxc
        when: percona_type == "seed"

      - name: configure | restart service
        service:
            name: mysql
            state: started

  when: _mysqld_installed.rc != 0

- name: configure | update root configuration file
  template:
      src: root.cnf.j2
      dest: "~root/.my.cnf"
      owner: root
      group: root
      mode: 0600

- name: configure | update clustercheck script
  template:
    src: clustercheck.j2
    dest: /usr/bin/clustercheck
    owner: root
    group: root
    mode: 0755

- name: configure | add mysqlchk service port definition
  lineinfile:
    path: /etc/services
    regexp: '^mysqlchk'
    line: "mysqlchk    {{ mysqlchk_port }}/tcp"

- name: configure | enable mysqlchk in xinetd
  template:
    src: mysqlchk.xinetd.j2
    dest: /etc/xinetd.d/mysqlchk
  notify:
    - restart xinetd
