- include: initialize.yml
- include: repository.yml
- include: install.yml
- include: configure.yml

- name: start and enable service
  service:
      name: mysql
      state: "{{ service_default_state | default('started') }}"
      enabled: "{{ service_default_enabled | default(true) | bool }}"
