- name: repository | add public key
  apt_key:
      id: "{{ apt_key }}"
      keyserver: keyserver.ubuntu.com
      state: present

- name: repository | add
  apt_repository:
      repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
      state: present
      update_cache: true
  with_items: "{{ apt_repositories }}"
